<?php

/**
 * @file
 * Contains achivements.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function achivements_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the achivements module.
    case 'help.page.achivements':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module store student achivements') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function achivements_theme() {
  return [
    'achivements' => [
      'render element' => 'children',
    ],
  ];
}
