<?php

/**
 * @file
 * Contains photo_gallery.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function photo_gallery_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the photo_gallery module.
    case 'help.page.photo_gallery':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is use for stylish photo gallery') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function photo_gallery_theme() {
  return [
    'photo_gallery' => [
      'render element' => 'children',
    ],
  ];
}
