<?php

/**
 * @file
 * Contains syllbus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function syllbus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the syllbus module.
    case 'help.page.syllbus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is store the university syllbus') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function syllbus_theme() {
  return [
    'syllbus' => [
      'render element' => 'children',
    ],
  ];
}
