<?php

/**
 * @file
 * Contains laboratory.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function laboratory_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the laboratory module.
    case 'help.page.laboratory':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module store laboratories details') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function laboratory_theme() {
  return [
    'laboratory' => [
      'render element' => 'children',
    ],
  ];
}
