<?php

/**
 * @file
 * Contains recruiters.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function recruiters_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the recruiters module.
    case 'help.page.recruiters':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module store details of companies') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function recruiters_theme() {
  return [
    'recruiters' => [
      'render element' => 'children',
    ],
  ];
}
