<?php

/**
 * @file
 * Contains members.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function members_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the members module.
    case 'help.page.members':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This modole store members details') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function members_theme() {
  return [
    'members' => [
      'render element' => 'children',
    ],
  ];
}
